🐛 fix(模块): 修正 FieldSet 的类型错误
sheinsight/shineout pull request #1666
Opened 2022-06-18 07:25 UTC by ityuany

应当将 Value 的范型作为 onInsert 的参数， 而不是整个 onInsert

2022-06-20 13:01 UTC, wenfangdu requested changes

2022-06-20 13:25 UTC, ityuany commented on src/@types/common.d.ts
> +export type LiteralUnion<T extends U, U> = T | (U & {});
是个好建议，已修正

2022-06-20 14:56 UTC, wenfangdu commented on src/@types/common.d.ts
> +export type LiteralUnion<T extends U, U> = T | (U & {});
@ityuany Type gymnastics 🤘

2022-06-23 03:11 UTC, leehaoChen commented on src/@types/common.d.ts
> +export type LiteralUnion<T = any> = T extends Record<any, any> ? (keyof T | Omit<string, keyof T>) : T
如果 T 是 不是对象   keygen 只能是 函数 或者true 建议改成
export type LiteralUnion<T = any> = T extends Record<any, any> ? (keyof T | Omit<string, keyof T>) : never

2022-06-23 06:25 UTC, merged